@startjson
{
    "evaluate": {
        "JDMn": {
            "definitions": {
                "decision": {
                    "decisionTable": {
                        "input": [
                            {
                                "inputExpression": {
                                    "label": "data",
                                    "typeRef": "date"
                                }
                            }
                        ],
                        "rule": [
                            {
                                "inputEntry": [
                                    {
                                        "text": "< 01/01/2023"
                                    }
                                ],
                                "outputEntry": {
                                    "text": "1"
                                }
                            },
                            {
                                "inputEntry": [
                                    {
                                        "text": "< 01/06/2023"
                                    }
                                ],
                                "outputEntry": {
                                    "text": "2"
                                }
                            },
                            {
                                "inputEntry": [
                                    {
                                        "text": "< 31/12/2023"
                                    }
                                ],
                                "outputEntry": {
                                    "text": "3"
                                }
                            },
                            {
                                "inputEntry": [
                                    {
                                        "text": "< 31/12/2024"
                                    }
                                ],
                                "outputEntry": {
                                    "text": "4"
                                }
                            },
                            {
                                "inputEntry": [
                                    {
                                        "text": ">= 31/12/2024"
                                    }
                                ],
                                "outputEntry": {
                                    "text": "5"
                                }
                            },
                            {
                                "inputEntry": [
                                    {
                                        "text": ""
                                    }
                                ],
                                "outputEntry": {
                                    "text": "999999999"
                                }
                            }
                        ]
                    }
                }
            }
        },
        "condition": {
            "data": "01/02/2023"
        }
    }
}
@endjson